AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  StateMachine

  Template for ECS

Parameters:
  CommitId:
    Type: String
    Description: "Commit ID of the code to be deployed"
    Default: "latest"

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster

  ECSRole:
    Type: AWS::IAM::Role
    Properties:
        RoleName: ECSRole
        AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ecs.amazonaws.com
                Action:
                - sts:AssumeRole
        ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole
            - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
            - arn:aws:iam::aws:policy/CloudWatchLogs

  ECSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "states:DescribeExecution"
              - "states:SendTaskSuccess"
              - "states:SendTaskFailure"
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              - "*"
      PolicyName: "ECSPolicy"
      Roles:
        - !Ref ECSRole

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode:  none
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !Ref ECSRole
      ContainerDefinitions:
        - Name: state
          Image: !Sub '{resolve:ssm:/state/repository-uri}:${CommitId}'
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/state
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs


# State machine role
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StateMachineRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole

  StateMachinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ecs:RunTask"
              - "ecs:DescribeTasks"
              - "ecs:StopTask"
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              - "*"
      PolicyName: "StateMachinePolicy"
      Roles:
        - !Ref StateMachineRole

  ECSStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/ecs_transformation.json
      Role: !Ref StateMachineRole
      DefinitionSubstitutions:
        ECS_CLUSTER: !Ref ECSCluster
        ECS_TASK_DEFINITION: !Ref TaskDefinition

